# This is a TOML document.
# Config parameters for gateway

# Identification for the gateway
[gatewayIdentification]
gatewayId = "b34c377c-65d8-4050-afa0-72c30023a65f"
gatewayName = "Gateway to be tested#1"
gatewayIpAddress = "127.0.0.1"
gatewaParentCallOnThisPort = 7100
gatewayChildrenCallOnThisPort = 7101
createdDateTime = ""

# Identification of the the domain that this gateway belongs to
[systemDomain]
gatewayDomainId = "c2fd9d3c-81e6-4641-8996-79c04d8eb4fb"
gatewayDomainName = "Custody Cash"

# Initial IP and Port for Parent Gateway/Fenix.
[parentgRPCAddress]
parentGatewayId ="6e38de17-d341-4eab-80da-297a09bc2e2d"
parentGatewayName = "Slave Parent Gateway"
parentGatewayServerAddress = "127.0.0.1"
parentGatewayServerPort = 7001
createdDateTime = ""
connectionToParentDoneAtLeastOnce = false
connectionToParentLastConnectionDateTime = ""

# The first port in port range for child-gateways or Plugins, for each ip address
[initialClientPort]
initialClientPort = 7660

# The logging level. Inly yse Debug for finding error otherwise use Info as standard logging level
[loggingLevel]
loggingLevel = "Debug"
# loggingLevel = "Info"
# loggingLevel = "Warning"

# Used for when gateway is used in Integration tests
[integrationTest]
usedInIntegrationTest = false
actAsParentGatewayInTest = false
actAsMainGatewayInTest = false
actAsChildGatewayInTest = false
startWithOutAnyParent = false