# This is a TOML document.
# Config parameters for gateway

# Identification for the gateway
[gatewayIdentification]
gatewayId = "6e38de17-d341-4eab-80da-297a09bc2e2d"
gatewayName = "Slave Parent Gateway"
gatewayIpAddress = "127.0.0.1"
gatewaParentCallOnThisPort = 7000
gatewayChildrenCallOnThisPort = 7001
createdDateTime = ""

# Identification of the the domain that this gateway belongs to
[systemDomain]
gatewayDomainId = "c2fd9d3c-81e6-4641-8996-79c04d8eb4fb"
gatewayDomainName = "Custody Cash"

# Initial IP and Port for Parent Gateway/Fenix.
[parentgRPCAddress]
parentGatewayId ="54ec25c1-769a-40b7-9edb-3987563c75ae"
parentGatewayName = "This is the name of the Parent  Gateway"
parentGatewayServerAddress = "127.0.0.1"
parentGatewayServerPort = 5999
createdDateTime = ""
connectionToParentDoneAtLeastOnce = false
connectionToParentLastConnectionDateTime = ""

# The first port in port range for child-gateways or Plugins, for each ip address
[initialClientPort]
initialClientPort = 6660

# The logging level. Inly yse Debug for finding error otherwise use Info as standard logging level
[loggingLevel]
loggingLevel = "Debug"
# loggingLevel = "Info"
# loggingLevel = "Warning"

# Used for when gateway is used in Integration tests
[integrationTest]
usedInIntegrationTest = true
actAsParentGatewayInTest = true
actAsMainGatewayInTest = false
actAsChildGatewayInTest = false
startWithOutAnyParent = true
