// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pluginDB.proto

package pluginDBgRPCApi

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Used for defining the current version of the proto-file
type CurrentVersionEnum int32

const (
	CurrentVersionEnum_VERSION_0_1_0 CurrentVersionEnum = 0
)

var CurrentVersionEnum_name = map[int32]string{
	0: "VERSION_0_1_0",
}

var CurrentVersionEnum_value = map[string]int32{
	"VERSION_0_1_0": 0,
}

func (x CurrentVersionEnum) String() string {
	return proto.EnumName(CurrentVersionEnum_name, int32(x))
}

func (CurrentVersionEnum) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_506f60f0cdd82b2e, []int{0}
}

// How the value should be saved
type ValueSaveTypeEnum int32

const (
	ValueSaveTypeEnum_BYTEARRAY ValueSaveTypeEnum = 0
	ValueSaveTypeEnum_STRING    ValueSaveTypeEnum = 1
	ValueSaveTypeEnum_BOTH      ValueSaveTypeEnum = 2
)

var ValueSaveTypeEnum_name = map[int32]string{
	0: "BYTEARRAY",
	1: "STRING",
	2: "BOTH",
}

var ValueSaveTypeEnum_value = map[string]int32{
	"BYTEARRAY": 0,
	"STRING":    1,
	"BOTH":      2,
}

func (x ValueSaveTypeEnum) String() string {
	return proto.EnumName(ValueSaveTypeEnum_name, int32(x))
}

func (ValueSaveTypeEnum) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_506f60f0cdd82b2e, []int{1}
}

// Message used for saving data into KeyValueStore
type WriteKeyValueMessage struct {
	Key                  string             `protobuf:"bytes,1,opt,name=Key,proto3" json:"Key,omitempty"`
	Bucket               string             `protobuf:"bytes,2,opt,name=Bucket,proto3" json:"Bucket,omitempty"`
	ValueSaveType        ValueSaveTypeEnum  `protobuf:"varint,3,opt,name=ValueSaveType,proto3,enum=pluginDBgRPCApi.ValueSaveTypeEnum" json:"ValueSaveType,omitempty"`
	Value                []byte             `protobuf:"bytes,4,opt,name=Value,proto3" json:"Value,omitempty"`
	ValueString          string             `protobuf:"bytes,5,opt,name=ValueString,proto3" json:"ValueString,omitempty"`
	CurrentVersion       CurrentVersionEnum `protobuf:"varint,6,opt,name=CurrentVersion,proto3,enum=pluginDBgRPCApi.CurrentVersionEnum" json:"CurrentVersion,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *WriteKeyValueMessage) Reset()         { *m = WriteKeyValueMessage{} }
func (m *WriteKeyValueMessage) String() string { return proto.CompactTextString(m) }
func (*WriteKeyValueMessage) ProtoMessage()    {}
func (*WriteKeyValueMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_506f60f0cdd82b2e, []int{0}
}

func (m *WriteKeyValueMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WriteKeyValueMessage.Unmarshal(m, b)
}
func (m *WriteKeyValueMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WriteKeyValueMessage.Marshal(b, m, deterministic)
}
func (m *WriteKeyValueMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WriteKeyValueMessage.Merge(m, src)
}
func (m *WriteKeyValueMessage) XXX_Size() int {
	return xxx_messageInfo_WriteKeyValueMessage.Size(m)
}
func (m *WriteKeyValueMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_WriteKeyValueMessage.DiscardUnknown(m)
}

var xxx_messageInfo_WriteKeyValueMessage proto.InternalMessageInfo

func (m *WriteKeyValueMessage) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *WriteKeyValueMessage) GetBucket() string {
	if m != nil {
		return m.Bucket
	}
	return ""
}

func (m *WriteKeyValueMessage) GetValueSaveType() ValueSaveTypeEnum {
	if m != nil {
		return m.ValueSaveType
	}
	return ValueSaveTypeEnum_BYTEARRAY
}

func (m *WriteKeyValueMessage) GetValue() []byte {
	if m != nil {
		return m.Value
	}
	return nil
}

func (m *WriteKeyValueMessage) GetValueString() string {
	if m != nil {
		return m.ValueString
	}
	return ""
}

func (m *WriteKeyValueMessage) GetCurrentVersion() CurrentVersionEnum {
	if m != nil {
		return m.CurrentVersion
	}
	return CurrentVersionEnum_VERSION_0_1_0
}

// Message used for reading data from KeyValueStore
type ReadKeyRequestMessage struct {
	Key                  string             `protobuf:"bytes,1,opt,name=Key,proto3" json:"Key,omitempty"`
	Bucket               string             `protobuf:"bytes,2,opt,name=Bucket,proto3" json:"Bucket,omitempty"`
	CurrentVersion       CurrentVersionEnum `protobuf:"varint,3,opt,name=CurrentVersion,proto3,enum=pluginDBgRPCApi.CurrentVersionEnum" json:"CurrentVersion,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *ReadKeyRequestMessage) Reset()         { *m = ReadKeyRequestMessage{} }
func (m *ReadKeyRequestMessage) String() string { return proto.CompactTextString(m) }
func (*ReadKeyRequestMessage) ProtoMessage()    {}
func (*ReadKeyRequestMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_506f60f0cdd82b2e, []int{1}
}

func (m *ReadKeyRequestMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReadKeyRequestMessage.Unmarshal(m, b)
}
func (m *ReadKeyRequestMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReadKeyRequestMessage.Marshal(b, m, deterministic)
}
func (m *ReadKeyRequestMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReadKeyRequestMessage.Merge(m, src)
}
func (m *ReadKeyRequestMessage) XXX_Size() int {
	return xxx_messageInfo_ReadKeyRequestMessage.Size(m)
}
func (m *ReadKeyRequestMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_ReadKeyRequestMessage.DiscardUnknown(m)
}

var xxx_messageInfo_ReadKeyRequestMessage proto.InternalMessageInfo

func (m *ReadKeyRequestMessage) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *ReadKeyRequestMessage) GetBucket() string {
	if m != nil {
		return m.Bucket
	}
	return ""
}

func (m *ReadKeyRequestMessage) GetCurrentVersion() CurrentVersionEnum {
	if m != nil {
		return m.CurrentVersion
	}
	return CurrentVersionEnum_VERSION_0_1_0
}

// Message used for returning data from KeyValueStore
type ValueResponseMessage struct {
	Key                  string            `protobuf:"bytes,1,opt,name=Key,proto3" json:"Key,omitempty"`
	Bucket               string            `protobuf:"bytes,2,opt,name=Bucket,proto3" json:"Bucket,omitempty"`
	ValueSaveType        ValueSaveTypeEnum `protobuf:"varint,3,opt,name=ValueSaveType,proto3,enum=pluginDBgRPCApi.ValueSaveTypeEnum" json:"ValueSaveType,omitempty"`
	Value                []byte            `protobuf:"bytes,4,opt,name=Value,proto3" json:"Value,omitempty"`
	ValueString          string            `protobuf:"bytes,5,opt,name=ValueString,proto3" json:"ValueString,omitempty"`
	UpdatedDateTime      string            `protobuf:"bytes,6,opt,name=updatedDateTime,proto3" json:"updatedDateTime,omitempty"`
	Acknack              bool              `protobuf:"varint,8,opt,name=acknack,proto3" json:"acknack,omitempty"`
	Comments             string            `protobuf:"bytes,9,opt,name=comments,proto3" json:"comments,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *ValueResponseMessage) Reset()         { *m = ValueResponseMessage{} }
func (m *ValueResponseMessage) String() string { return proto.CompactTextString(m) }
func (*ValueResponseMessage) ProtoMessage()    {}
func (*ValueResponseMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_506f60f0cdd82b2e, []int{2}
}

func (m *ValueResponseMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ValueResponseMessage.Unmarshal(m, b)
}
func (m *ValueResponseMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ValueResponseMessage.Marshal(b, m, deterministic)
}
func (m *ValueResponseMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ValueResponseMessage.Merge(m, src)
}
func (m *ValueResponseMessage) XXX_Size() int {
	return xxx_messageInfo_ValueResponseMessage.Size(m)
}
func (m *ValueResponseMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_ValueResponseMessage.DiscardUnknown(m)
}

var xxx_messageInfo_ValueResponseMessage proto.InternalMessageInfo

func (m *ValueResponseMessage) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *ValueResponseMessage) GetBucket() string {
	if m != nil {
		return m.Bucket
	}
	return ""
}

func (m *ValueResponseMessage) GetValueSaveType() ValueSaveTypeEnum {
	if m != nil {
		return m.ValueSaveType
	}
	return ValueSaveTypeEnum_BYTEARRAY
}

func (m *ValueResponseMessage) GetValue() []byte {
	if m != nil {
		return m.Value
	}
	return nil
}

func (m *ValueResponseMessage) GetValueString() string {
	if m != nil {
		return m.ValueString
	}
	return ""
}

func (m *ValueResponseMessage) GetUpdatedDateTime() string {
	if m != nil {
		return m.UpdatedDateTime
	}
	return ""
}

func (m *ValueResponseMessage) GetAcknack() bool {
	if m != nil {
		return m.Acknack
	}
	return false
}

func (m *ValueResponseMessage) GetComments() string {
	if m != nil {
		return m.Comments
	}
	return ""
}

// Ack/Nack- Response message with comment
type AckNackResponse struct {
	Acknack              bool     `protobuf:"varint,1,opt,name=acknack,proto3" json:"acknack,omitempty"`
	Comments             string   `protobuf:"bytes,2,opt,name=comments,proto3" json:"comments,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AckNackResponse) Reset()         { *m = AckNackResponse{} }
func (m *AckNackResponse) String() string { return proto.CompactTextString(m) }
func (*AckNackResponse) ProtoMessage()    {}
func (*AckNackResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_506f60f0cdd82b2e, []int{3}
}

func (m *AckNackResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AckNackResponse.Unmarshal(m, b)
}
func (m *AckNackResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AckNackResponse.Marshal(b, m, deterministic)
}
func (m *AckNackResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AckNackResponse.Merge(m, src)
}
func (m *AckNackResponse) XXX_Size() int {
	return xxx_messageInfo_AckNackResponse.Size(m)
}
func (m *AckNackResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AckNackResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AckNackResponse proto.InternalMessageInfo

func (m *AckNackResponse) GetAcknack() bool {
	if m != nil {
		return m.Acknack
	}
	return false
}

func (m *AckNackResponse) GetComments() string {
	if m != nil {
		return m.Comments
	}
	return ""
}

func init() {
	proto.RegisterEnum("pluginDBgRPCApi.CurrentVersionEnum", CurrentVersionEnum_name, CurrentVersionEnum_value)
	proto.RegisterEnum("pluginDBgRPCApi.ValueSaveTypeEnum", ValueSaveTypeEnum_name, ValueSaveTypeEnum_value)
	proto.RegisterType((*WriteKeyValueMessage)(nil), "pluginDBgRPCApi.WriteKeyValueMessage")
	proto.RegisterType((*ReadKeyRequestMessage)(nil), "pluginDBgRPCApi.ReadKeyRequestMessage")
	proto.RegisterType((*ValueResponseMessage)(nil), "pluginDBgRPCApi.ValueResponseMessage")
	proto.RegisterType((*AckNackResponse)(nil), "pluginDBgRPCApi.AckNackResponse")
}

func init() { proto.RegisterFile("pluginDB.proto", fileDescriptor_506f60f0cdd82b2e) }

var fileDescriptor_506f60f0cdd82b2e = []byte{
	// 452 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xd4, 0x54, 0xcd, 0x6e, 0xd3, 0x40,
	0x10, 0xce, 0x26, 0x6d, 0x70, 0x06, 0x92, 0xb8, 0xa3, 0x80, 0x56, 0x39, 0x59, 0x46, 0x05, 0xab,
	0x87, 0xa8, 0x94, 0x0b, 0xd7, 0xa4, 0x0d, 0x6d, 0x15, 0x91, 0x56, 0x1b, 0x2b, 0xa8, 0xa7, 0x68,
	0x71, 0x46, 0xc1, 0x72, 0xfd, 0x83, 0xbd, 0x46, 0xca, 0x4b, 0xc0, 0x3b, 0xf0, 0x52, 0xbc, 0x0e,
	0x62, 0x93, 0xa0, 0xda, 0x0e, 0x07, 0xb8, 0xf5, 0xe6, 0x6f, 0x34, 0xdf, 0xcc, 0xe7, 0x6f, 0x66,
	0x16, 0x3a, 0xc9, 0x7d, 0xbe, 0xf2, 0xa3, 0x8b, 0xd1, 0x20, 0x49, 0x63, 0x15, 0x63, 0x77, 0x87,
	0x57, 0xe2, 0xf6, 0x7c, 0x98, 0xf8, 0xf6, 0xf7, 0x3a, 0xf4, 0x3e, 0xa6, 0xbe, 0xa2, 0x09, 0xad,
	0xe7, 0xf2, 0x3e, 0xa7, 0x0f, 0x94, 0x65, 0x72, 0x45, 0x68, 0x42, 0x63, 0x42, 0x6b, 0xce, 0x2c,
	0xe6, 0xb4, 0xc4, 0xef, 0x4f, 0x7c, 0x01, 0xcd, 0x51, 0xee, 0x05, 0xa4, 0x78, 0x5d, 0x07, 0xb7,
	0x08, 0xaf, 0xa0, 0xad, 0x99, 0x33, 0xf9, 0x95, 0xdc, 0x75, 0x42, 0xbc, 0x61, 0x31, 0xa7, 0x73,
	0x66, 0x0f, 0x4a, 0xbd, 0x06, 0x85, 0xac, 0x71, 0x94, 0x87, 0xa2, 0x48, 0xc4, 0x1e, 0x1c, 0xea,
	0x00, 0x3f, 0xb0, 0x98, 0xf3, 0x4c, 0x6c, 0x00, 0x5a, 0xf0, 0x74, 0x93, 0xa6, 0x52, 0x3f, 0x5a,
	0xf1, 0x43, 0xdd, 0xfc, 0x61, 0x08, 0x27, 0xd0, 0x39, 0xcf, 0xd3, 0x94, 0x22, 0x35, 0xa7, 0x34,
	0xf3, 0xe3, 0x88, 0x37, 0xb5, 0x84, 0x97, 0x15, 0x09, 0xc5, 0x34, 0xad, 0xa1, 0x44, 0xb5, 0xbf,
	0x31, 0x78, 0x2e, 0x48, 0x2e, 0x27, 0xb4, 0x16, 0xf4, 0x25, 0xa7, 0x4c, 0xfd, 0xbb, 0x25, 0x55,
	0x41, 0x8d, 0xff, 0x17, 0xf4, 0xa3, 0x0e, 0x3d, 0xfd, 0xb7, 0x82, 0xb2, 0x24, 0x8e, 0xb2, 0x47,
	0x39, 0x22, 0x07, 0xba, 0x79, 0xb2, 0x94, 0x8a, 0x96, 0x17, 0x52, 0x91, 0xeb, 0x87, 0xa4, 0x67,
	0xd4, 0x12, 0xe5, 0x30, 0x72, 0x78, 0x22, 0xbd, 0x20, 0x92, 0x5e, 0xc0, 0x0d, 0x8b, 0x39, 0x86,
	0xd8, 0x41, 0xec, 0x83, 0xe1, 0xc5, 0x61, 0x48, 0x91, 0xca, 0x78, 0x4b, 0x93, 0xff, 0x60, 0xfb,
	0x12, 0xba, 0x43, 0x2f, 0x98, 0x4a, 0x2f, 0xd8, 0xb9, 0xf4, 0xb0, 0x10, 0xfb, 0x7b, 0xa1, 0x7a,
	0xb1, 0xd0, 0xc9, 0x6b, 0xc0, 0xea, 0x4c, 0xf0, 0x08, 0xda, 0xf3, 0xb1, 0x98, 0x5d, 0xdf, 0x4c,
	0x17, 0xa7, 0x8b, 0x37, 0x8b, 0x53, 0xb3, 0x76, 0xf2, 0x0e, 0x8e, 0x2a, 0x6e, 0x61, 0x1b, 0x5a,
	0xa3, 0x3b, 0x77, 0x3c, 0x14, 0x62, 0x78, 0x67, 0xd6, 0x10, 0xa0, 0x39, 0x73, 0xc5, 0xf5, 0xf4,
	0xd2, 0x64, 0x68, 0xc0, 0xc1, 0xe8, 0xc6, 0xbd, 0x32, 0xeb, 0x67, 0x3f, 0x19, 0x18, 0xb7, 0x5b,
	0xe3, 0x51, 0x6e, 0xef, 0xcf, 0x8d, 0x77, 0x17, 0x38, 0x53, 0x71, 0x4a, 0x78, 0x5c, 0x99, 0xcd,
	0xbe, 0x33, 0xed, 0x5b, 0x95, 0xb4, 0x92, 0x0d, 0x76, 0x0d, 0x3f, 0x6f, 0x16, 0xfa, 0x7d, 0x1a,
	0x87, 0xc5, 0x1e, 0xaf, 0x2a, 0xe4, 0xbd, 0x8b, 0xdf, 0x3f, 0xde, 0xbf, 0x27, 0xa5, 0x7d, 0xb4,
	0x6b, 0x9f, 0x9a, 0xfa, 0x95, 0x79, 0xfb, 0x2b, 0x00, 0x00, 0xff, 0xff, 0xdc, 0x50, 0x4c, 0xdd,
	0x77, 0x04, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// PluginDBClient is the client API for PluginDB service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type PluginDBClient interface {
	// ***********************************************************************************
	// Save Data method
	// ***********************************************************************************
	WriteToKeyValueStore(ctx context.Context, in *WriteKeyValueMessage, opts ...grpc.CallOption) (*AckNackResponse, error)
	// ***********************************************************************************
	// Read Data Method
	// ***********************************************************************************
	ReadFromKeyValueStore(ctx context.Context, in *ReadKeyRequestMessage, opts ...grpc.CallOption) (*ValueResponseMessage, error)
}

type pluginDBClient struct {
	cc *grpc.ClientConn
}

func NewPluginDBClient(cc *grpc.ClientConn) PluginDBClient {
	return &pluginDBClient{cc}
}

func (c *pluginDBClient) WriteToKeyValueStore(ctx context.Context, in *WriteKeyValueMessage, opts ...grpc.CallOption) (*AckNackResponse, error) {
	out := new(AckNackResponse)
	err := c.cc.Invoke(ctx, "/pluginDBgRPCApi.PluginDB/WriteToKeyValueStore", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pluginDBClient) ReadFromKeyValueStore(ctx context.Context, in *ReadKeyRequestMessage, opts ...grpc.CallOption) (*ValueResponseMessage, error) {
	out := new(ValueResponseMessage)
	err := c.cc.Invoke(ctx, "/pluginDBgRPCApi.PluginDB/ReadFromKeyValueStore", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PluginDBServer is the server API for PluginDB service.
type PluginDBServer interface {
	// ***********************************************************************************
	// Save Data method
	// ***********************************************************************************
	WriteToKeyValueStore(context.Context, *WriteKeyValueMessage) (*AckNackResponse, error)
	// ***********************************************************************************
	// Read Data Method
	// ***********************************************************************************
	ReadFromKeyValueStore(context.Context, *ReadKeyRequestMessage) (*ValueResponseMessage, error)
}

func RegisterPluginDBServer(s *grpc.Server, srv PluginDBServer) {
	s.RegisterService(&_PluginDB_serviceDesc, srv)
}

func _PluginDB_WriteToKeyValueStore_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WriteKeyValueMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PluginDBServer).WriteToKeyValueStore(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pluginDBgRPCApi.PluginDB/WriteToKeyValueStore",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PluginDBServer).WriteToKeyValueStore(ctx, req.(*WriteKeyValueMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _PluginDB_ReadFromKeyValueStore_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReadKeyRequestMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PluginDBServer).ReadFromKeyValueStore(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pluginDBgRPCApi.PluginDB/ReadFromKeyValueStore",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PluginDBServer).ReadFromKeyValueStore(ctx, req.(*ReadKeyRequestMessage))
	}
	return interceptor(ctx, in, info, handler)
}

var _PluginDB_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pluginDBgRPCApi.PluginDB",
	HandlerType: (*PluginDBServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "WriteToKeyValueStore",
			Handler:    _PluginDB_WriteToKeyValueStore_Handler,
		},
		{
			MethodName: "ReadFromKeyValueStore",
			Handler:    _PluginDB_ReadFromKeyValueStore_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pluginDB.proto",
}
