package common_code

// ChannelType
const ChannelTypeInformationMessageTowardsFenix = "ChannelTypeInformationMessageTowardsFenix"
const ChannelTypeTestInstructionTimeOutMessageTowardsFenix = "ChannelTypeTestInstructionTimeOutMessageTowardsFenix"
const ChannelTypeTestExecutionLogMessageTowardsFenix = "ChannelTypeTestExecutionLogMessageTowardsFenix"
const ChannelTypeSupportedTestDataDomainsMessageTowardsFenix = "ChannelTypeSupportedTestDataDomainsMessageTowardsFenix"
const ChannelTypeAvailbleTestInstructionsAtPluginMessageTowardsFenix = "ChannelTypeAvailbleTestInstructionsAtPluginMessageTowardsFenix"
const ChannelTypeAvailbleTestContainersAtPluginMessageTowardsFenix = "ChannelTypeAvailbleTestContainersAtPluginMessageTowardsFenix"
const ChannelTypeTestInstructionExecutionResultMessageTowardsFenix = "ChannelTypeTestInstructionExecutionResultMessageTowardsFenix"
const ChannelTypeSupportedTestDataDomainsWithHeadersMessageTowardsFenix = "ChannelTypeSupportedTestDataDomainsWithHeadersMessageTowardsFenix"

type GRPCServerTowardsFenixStruct struct{}
