// Code generated by protoc-gen-go. DO NOT EDIT.
// source: gateway_towards_plugin_grpc.proto

package Gateway_gRPC_api

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// The TestInstructionAttribute can be one of the folowing types
type TestInstructionAttributeTypeEnum int32

const (
	TestInstructionAttributeTypeEnum_TextBox      TestInstructionAttributeTypeEnum = 0
	TestInstructionAttributeTypeEnum_ComboBox     TestInstructionAttributeTypeEnum = 1
	TestInstructionAttributeTypeEnum_FileSelector TestInstructionAttributeTypeEnum = 2
)

var TestInstructionAttributeTypeEnum_name = map[int32]string{
	0: "TextBox",
	1: "ComboBox",
	2: "FileSelector",
}

var TestInstructionAttributeTypeEnum_value = map[string]int32{
	"TextBox":      0,
	"ComboBox":     1,
	"FileSelector": 2,
}

func (x TestInstructionAttributeTypeEnum) String() string {
	return proto.EnumName(TestInstructionAttributeTypeEnum_name, int32(x))
}

func (TestInstructionAttributeTypeEnum) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_9bd1c4b0181b0d9a, []int{0}
}

// The status used within a Gateway can be one of the following types
type DbStatusEnum int32

const (
	DbStatusEnum_TESTINSTRUCTION_RECEIVED_FROM_PARENT DbStatusEnum = 0
	DbStatusEnum_TESTINSTRUCTION_SENT_TO_CHILD        DbStatusEnum = 1
	DbStatusEnum_RESULT_RECEIVED_FROM_CHILD           DbStatusEnum = 2
	DbStatusEnum_RESULT_SENT_TO_TO_PARENT             DbStatusEnum = 3
)

var DbStatusEnum_name = map[int32]string{
	0: "TESTINSTRUCTION_RECEIVED_FROM_PARENT",
	1: "TESTINSTRUCTION_SENT_TO_CHILD",
	2: "RESULT_RECEIVED_FROM_CHILD",
	3: "RESULT_SENT_TO_TO_PARENT",
}

var DbStatusEnum_value = map[string]int32{
	"TESTINSTRUCTION_RECEIVED_FROM_PARENT": 0,
	"TESTINSTRUCTION_SENT_TO_CHILD":        1,
	"RESULT_RECEIVED_FROM_CHILD":           2,
	"RESULT_SENT_TO_TO_PARENT":             3,
}

func (x DbStatusEnum) String() string {
	return proto.EnumName(DbStatusEnum_name, int32(x))
}

func (DbStatusEnum) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_9bd1c4b0181b0d9a, []int{1}
}

//  A RunTime version of the TestInstruction sent from Fenix towards a Plugin
type TestInstruction_RT struct {
	OriginalSenderId               string                         `protobuf:"bytes,1,opt,name=OriginalSenderId,proto3" json:"OriginalSenderId,omitempty"`
	OriginalSenderName             string                         `protobuf:"bytes,2,opt,name=OriginalSenderName,proto3" json:"OriginalSenderName,omitempty"`
	SenderId                       string                         `protobuf:"bytes,3,opt,name=SenderId,proto3" json:"SenderId,omitempty"`
	SenderName                     string                         `protobuf:"bytes,4,opt,name=SenderName,proto3" json:"SenderName,omitempty"`
	TestInstructionTypeGuid        string                         `protobuf:"bytes,5,opt,name=TestInstructionTypeGuid,proto3" json:"TestInstructionTypeGuid,omitempty"`
	TestInstructionGuid            string                         `protobuf:"bytes,6,opt,name=TestInstructionGuid,proto3" json:"TestInstructionGuid,omitempty"`
	TestInstructionTypeName        string                         `protobuf:"bytes,7,opt,name=TestInstructionTypeName,proto3" json:"TestInstructionTypeName,omitempty"`
	PluginId                       string                         `protobuf:"bytes,8,opt,name=PluginId,proto3" json:"PluginId,omitempty"`
	PluginName                     string                         `protobuf:"bytes,9,opt,name=PluginName,proto3" json:"PluginName,omitempty"`
	TestMainGroupGuid_RT           string                         `protobuf:"bytes,10,opt,name=TestMainGroupGuid_RT,json=TestMainGroupGuidRT,proto3" json:"TestMainGroupGuid_RT,omitempty"`
	TestInstructionAttributes      []*TestInstructionAttribute_RT `protobuf:"bytes,11,rep,name=TestInstructionAttributes,proto3" json:"TestInstructionAttributes,omitempty"`
	TestInstructionCreatedDateTime string                         `protobuf:"bytes,12,opt,name=TestInstructionCreatedDateTime,proto3" json:"TestInstructionCreatedDateTime,omitempty"`
	TestInstructionSentDateTime    []string                       `protobuf:"bytes,13,rep,name=TestInstructionSentDateTime,proto3" json:"TestInstructionSentDateTime,omitempty"`
	ChoosenLandingZone             string                         `protobuf:"bytes,14,opt,name=ChoosenLandingZone,proto3" json:"ChoosenLandingZone,omitempty"`
	Metadata                       *TestInstructionRTMetadata     `protobuf:"bytes,15,opt,name=Metadata,proto3" json:"Metadata,omitempty"`
	OrginalCreateDateTime          string                         `protobuf:"bytes,16,opt,name=OrginalCreateDateTime,proto3" json:"OrginalCreateDateTime,omitempty"`
	MessageId                      string                         `protobuf:"bytes,17,opt,name=MessageId,proto3" json:"MessageId,omitempty"`
	XXX_NoUnkeyedLiteral           struct{}                       `json:"-"`
	XXX_unrecognized               []byte                         `json:"-"`
	XXX_sizecache                  int32                          `json:"-"`
}

func (m *TestInstruction_RT) Reset()         { *m = TestInstruction_RT{} }
func (m *TestInstruction_RT) String() string { return proto.CompactTextString(m) }
func (*TestInstruction_RT) ProtoMessage()    {}
func (*TestInstruction_RT) Descriptor() ([]byte, []int) {
	return fileDescriptor_9bd1c4b0181b0d9a, []int{0}
}

func (m *TestInstruction_RT) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TestInstruction_RT.Unmarshal(m, b)
}
func (m *TestInstruction_RT) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TestInstruction_RT.Marshal(b, m, deterministic)
}
func (m *TestInstruction_RT) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TestInstruction_RT.Merge(m, src)
}
func (m *TestInstruction_RT) XXX_Size() int {
	return xxx_messageInfo_TestInstruction_RT.Size(m)
}
func (m *TestInstruction_RT) XXX_DiscardUnknown() {
	xxx_messageInfo_TestInstruction_RT.DiscardUnknown(m)
}

var xxx_messageInfo_TestInstruction_RT proto.InternalMessageInfo

func (m *TestInstruction_RT) GetOriginalSenderId() string {
	if m != nil {
		return m.OriginalSenderId
	}
	return ""
}

func (m *TestInstruction_RT) GetOriginalSenderName() string {
	if m != nil {
		return m.OriginalSenderName
	}
	return ""
}

func (m *TestInstruction_RT) GetSenderId() string {
	if m != nil {
		return m.SenderId
	}
	return ""
}

func (m *TestInstruction_RT) GetSenderName() string {
	if m != nil {
		return m.SenderName
	}
	return ""
}

func (m *TestInstruction_RT) GetTestInstructionTypeGuid() string {
	if m != nil {
		return m.TestInstructionTypeGuid
	}
	return ""
}

func (m *TestInstruction_RT) GetTestInstructionGuid() string {
	if m != nil {
		return m.TestInstructionGuid
	}
	return ""
}

func (m *TestInstruction_RT) GetTestInstructionTypeName() string {
	if m != nil {
		return m.TestInstructionTypeName
	}
	return ""
}

func (m *TestInstruction_RT) GetPluginId() string {
	if m != nil {
		return m.PluginId
	}
	return ""
}

func (m *TestInstruction_RT) GetPluginName() string {
	if m != nil {
		return m.PluginName
	}
	return ""
}

func (m *TestInstruction_RT) GetTestMainGroupGuid_RT() string {
	if m != nil {
		return m.TestMainGroupGuid_RT
	}
	return ""
}

func (m *TestInstruction_RT) GetTestInstructionAttributes() []*TestInstructionAttribute_RT {
	if m != nil {
		return m.TestInstructionAttributes
	}
	return nil
}

func (m *TestInstruction_RT) GetTestInstructionCreatedDateTime() string {
	if m != nil {
		return m.TestInstructionCreatedDateTime
	}
	return ""
}

func (m *TestInstruction_RT) GetTestInstructionSentDateTime() []string {
	if m != nil {
		return m.TestInstructionSentDateTime
	}
	return nil
}

func (m *TestInstruction_RT) GetChoosenLandingZone() string {
	if m != nil {
		return m.ChoosenLandingZone
	}
	return ""
}

func (m *TestInstruction_RT) GetMetadata() *TestInstructionRTMetadata {
	if m != nil {
		return m.Metadata
	}
	return nil
}

func (m *TestInstruction_RT) GetOrginalCreateDateTime() string {
	if m != nil {
		return m.OrginalCreateDateTime
	}
	return ""
}

func (m *TestInstruction_RT) GetMessageId() string {
	if m != nil {
		return m.MessageId
	}
	return ""
}

//  An attribute with it's type and value
type TestInstructionAttribute_RT struct {
	TestInstructionAttributeGuid  string                           `protobuf:"bytes,1,opt,name=TestInstructionAttributeGuid,proto3" json:"TestInstructionAttributeGuid,omitempty"`
	TestInstructionAttributeName  string                           `protobuf:"bytes,2,opt,name=TestInstructionAttributeName,proto3" json:"TestInstructionAttributeName,omitempty"`
	TestInstructionAttributeType  TestInstructionAttributeTypeEnum `protobuf:"varint,3,opt,name=TestInstructionAttributeType,proto3,enum=Gateway_gRPC_api.TestInstructionAttributeTypeEnum" json:"TestInstructionAttributeType,omitempty"`
	TestInstructionAttributeValue string                           `protobuf:"bytes,4,opt,name=TestInstructionAttributeValue,proto3" json:"TestInstructionAttributeValue,omitempty"`
	XXX_NoUnkeyedLiteral          struct{}                         `json:"-"`
	XXX_unrecognized              []byte                           `json:"-"`
	XXX_sizecache                 int32                            `json:"-"`
}

func (m *TestInstructionAttribute_RT) Reset()         { *m = TestInstructionAttribute_RT{} }
func (m *TestInstructionAttribute_RT) String() string { return proto.CompactTextString(m) }
func (*TestInstructionAttribute_RT) ProtoMessage()    {}
func (*TestInstructionAttribute_RT) Descriptor() ([]byte, []int) {
	return fileDescriptor_9bd1c4b0181b0d9a, []int{1}
}

func (m *TestInstructionAttribute_RT) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TestInstructionAttribute_RT.Unmarshal(m, b)
}
func (m *TestInstructionAttribute_RT) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TestInstructionAttribute_RT.Marshal(b, m, deterministic)
}
func (m *TestInstructionAttribute_RT) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TestInstructionAttribute_RT.Merge(m, src)
}
func (m *TestInstructionAttribute_RT) XXX_Size() int {
	return xxx_messageInfo_TestInstructionAttribute_RT.Size(m)
}
func (m *TestInstructionAttribute_RT) XXX_DiscardUnknown() {
	xxx_messageInfo_TestInstructionAttribute_RT.DiscardUnknown(m)
}

var xxx_messageInfo_TestInstructionAttribute_RT proto.InternalMessageInfo

func (m *TestInstructionAttribute_RT) GetTestInstructionAttributeGuid() string {
	if m != nil {
		return m.TestInstructionAttributeGuid
	}
	return ""
}

func (m *TestInstructionAttribute_RT) GetTestInstructionAttributeName() string {
	if m != nil {
		return m.TestInstructionAttributeName
	}
	return ""
}

func (m *TestInstructionAttribute_RT) GetTestInstructionAttributeType() TestInstructionAttributeTypeEnum {
	if m != nil {
		return m.TestInstructionAttributeType
	}
	return TestInstructionAttributeTypeEnum_TextBox
}

func (m *TestInstructionAttribute_RT) GetTestInstructionAttributeValue() string {
	if m != nil {
		return m.TestInstructionAttributeValue
	}
	return ""
}

// Metadata used for sending the the TestInstruction to correct receiver
type TestInstructionRTMetadata struct {
	CreatedDateTimeFenix    string       `protobuf:"bytes,1,opt,name=CreatedDateTimeFenix,proto3" json:"CreatedDateTimeFenix,omitempty"`
	CreatedDateTimePlugin   string       `protobuf:"bytes,2,opt,name=CreatedDateTimePlugin,proto3" json:"CreatedDateTimePlugin,omitempty"`
	LastUpdatedDateTimeInDB string       `protobuf:"bytes,3,opt,name=LastUpdatedDateTimeInDB,proto3" json:"LastUpdatedDateTimeInDB,omitempty"`
	DbStatusEnum            DbStatusEnum `protobuf:"varint,4,opt,name=DbStatusEnum,proto3,enum=Gateway_gRPC_api.DbStatusEnum" json:"DbStatusEnum,omitempty"`
	XXX_NoUnkeyedLiteral    struct{}     `json:"-"`
	XXX_unrecognized        []byte       `json:"-"`
	XXX_sizecache           int32        `json:"-"`
}

func (m *TestInstructionRTMetadata) Reset()         { *m = TestInstructionRTMetadata{} }
func (m *TestInstructionRTMetadata) String() string { return proto.CompactTextString(m) }
func (*TestInstructionRTMetadata) ProtoMessage()    {}
func (*TestInstructionRTMetadata) Descriptor() ([]byte, []int) {
	return fileDescriptor_9bd1c4b0181b0d9a, []int{2}
}

func (m *TestInstructionRTMetadata) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TestInstructionRTMetadata.Unmarshal(m, b)
}
func (m *TestInstructionRTMetadata) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TestInstructionRTMetadata.Marshal(b, m, deterministic)
}
func (m *TestInstructionRTMetadata) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TestInstructionRTMetadata.Merge(m, src)
}
func (m *TestInstructionRTMetadata) XXX_Size() int {
	return xxx_messageInfo_TestInstructionRTMetadata.Size(m)
}
func (m *TestInstructionRTMetadata) XXX_DiscardUnknown() {
	xxx_messageInfo_TestInstructionRTMetadata.DiscardUnknown(m)
}

var xxx_messageInfo_TestInstructionRTMetadata proto.InternalMessageInfo

func (m *TestInstructionRTMetadata) GetCreatedDateTimeFenix() string {
	if m != nil {
		return m.CreatedDateTimeFenix
	}
	return ""
}

func (m *TestInstructionRTMetadata) GetCreatedDateTimePlugin() string {
	if m != nil {
		return m.CreatedDateTimePlugin
	}
	return ""
}

func (m *TestInstructionRTMetadata) GetLastUpdatedDateTimeInDB() string {
	if m != nil {
		return m.LastUpdatedDateTimeInDB
	}
	return ""
}

func (m *TestInstructionRTMetadata) GetDbStatusEnum() DbStatusEnum {
	if m != nil {
		return m.DbStatusEnum
	}
	return DbStatusEnum_TESTINSTRUCTION_RECEIVED_FROM_PARENT
}

// Message to get supported TestData-domains from a plugin
type SupportedTestDataDomainsRequest struct {
	OriginalSenderId     string   `protobuf:"bytes,1,opt,name=OriginalSenderId,proto3" json:"OriginalSenderId,omitempty"`
	OriginalSenderName   string   `protobuf:"bytes,2,opt,name=OriginalSenderName,proto3" json:"OriginalSenderName,omitempty"`
	SenderId             string   `protobuf:"bytes,3,opt,name=SenderId,proto3" json:"SenderId,omitempty"`
	SenderName           string   `protobuf:"bytes,4,opt,name=SenderName,proto3" json:"SenderName,omitempty"`
	PluginId             string   `protobuf:"bytes,5,opt,name=PluginId,proto3" json:"PluginId,omitempty"`
	PluginName           string   `protobuf:"bytes,6,opt,name=PluginName,proto3" json:"PluginName,omitempty"`
	MessageId            string   `protobuf:"bytes,7,opt,name=MessageId,proto3" json:"MessageId,omitempty"`
	CreatedDateTime      string   `protobuf:"bytes,8,opt,name=CreatedDateTime,proto3" json:"CreatedDateTime,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SupportedTestDataDomainsRequest) Reset()         { *m = SupportedTestDataDomainsRequest{} }
func (m *SupportedTestDataDomainsRequest) String() string { return proto.CompactTextString(m) }
func (*SupportedTestDataDomainsRequest) ProtoMessage()    {}
func (*SupportedTestDataDomainsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9bd1c4b0181b0d9a, []int{3}
}

func (m *SupportedTestDataDomainsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SupportedTestDataDomainsRequest.Unmarshal(m, b)
}
func (m *SupportedTestDataDomainsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SupportedTestDataDomainsRequest.Marshal(b, m, deterministic)
}
func (m *SupportedTestDataDomainsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SupportedTestDataDomainsRequest.Merge(m, src)
}
func (m *SupportedTestDataDomainsRequest) XXX_Size() int {
	return xxx_messageInfo_SupportedTestDataDomainsRequest.Size(m)
}
func (m *SupportedTestDataDomainsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SupportedTestDataDomainsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SupportedTestDataDomainsRequest proto.InternalMessageInfo

func (m *SupportedTestDataDomainsRequest) GetOriginalSenderId() string {
	if m != nil {
		return m.OriginalSenderId
	}
	return ""
}

func (m *SupportedTestDataDomainsRequest) GetOriginalSenderName() string {
	if m != nil {
		return m.OriginalSenderName
	}
	return ""
}

func (m *SupportedTestDataDomainsRequest) GetSenderId() string {
	if m != nil {
		return m.SenderId
	}
	return ""
}

func (m *SupportedTestDataDomainsRequest) GetSenderName() string {
	if m != nil {
		return m.SenderName
	}
	return ""
}

func (m *SupportedTestDataDomainsRequest) GetPluginId() string {
	if m != nil {
		return m.PluginId
	}
	return ""
}

func (m *SupportedTestDataDomainsRequest) GetPluginName() string {
	if m != nil {
		return m.PluginName
	}
	return ""
}

func (m *SupportedTestDataDomainsRequest) GetMessageId() string {
	if m != nil {
		return m.MessageId
	}
	return ""
}

func (m *SupportedTestDataDomainsRequest) GetCreatedDateTime() string {
	if m != nil {
		return m.CreatedDateTime
	}
	return ""
}

// Message with filter values to have the testdata plugin retrieve correct testdata to use
type TestDataFilterValuesRequest struct {
	PluginId                  string                  `protobuf:"bytes,1,opt,name=PluginId,proto3" json:"PluginId,omitempty"`
	PluginName                string                  `protobuf:"bytes,2,opt,name=PluginName,proto3" json:"PluginName,omitempty"`
	MessageId                 string                  `protobuf:"bytes,3,opt,name=MessageId,proto3" json:"MessageId,omitempty"`
	TestDataDomainId          string                  `protobuf:"bytes,4,opt,name=TestDataDomainId,proto3" json:"TestDataDomainId,omitempty"`
	StartLineOfResultSet      int64                   `protobuf:"varint,6,opt,name=StartLineOfResultSet,proto3" json:"StartLineOfResultSet,omitempty"`
	MaxNumberOffLinesInResult int64                   `protobuf:"varint,7,opt,name=MaxNumberOffLinesInResult,proto3" json:"MaxNumberOffLinesInResult,omitempty"`
	TestDataType              TestDataFormatTypeEnum  `protobuf:"varint,8,opt,name=TestDataType,proto3,enum=Gateway_gRPC_api.TestDataFormatTypeEnum" json:"TestDataType,omitempty"`
	TestDataFIlterHeaders     []*TestDataFilterHeader `protobuf:"bytes,9,rep,name=TestDataFIlterHeaders,proto3" json:"TestDataFIlterHeaders,omitempty"`
	OrginalCreateDateTime     string                  `protobuf:"bytes,10,opt,name=OrginalCreateDateTime,proto3" json:"OrginalCreateDateTime,omitempty"`
	XXX_NoUnkeyedLiteral      struct{}                `json:"-"`
	XXX_unrecognized          []byte                  `json:"-"`
	XXX_sizecache             int32                   `json:"-"`
}

func (m *TestDataFilterValuesRequest) Reset()         { *m = TestDataFilterValuesRequest{} }
func (m *TestDataFilterValuesRequest) String() string { return proto.CompactTextString(m) }
func (*TestDataFilterValuesRequest) ProtoMessage()    {}
func (*TestDataFilterValuesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9bd1c4b0181b0d9a, []int{4}
}

func (m *TestDataFilterValuesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TestDataFilterValuesRequest.Unmarshal(m, b)
}
func (m *TestDataFilterValuesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TestDataFilterValuesRequest.Marshal(b, m, deterministic)
}
func (m *TestDataFilterValuesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TestDataFilterValuesRequest.Merge(m, src)
}
func (m *TestDataFilterValuesRequest) XXX_Size() int {
	return xxx_messageInfo_TestDataFilterValuesRequest.Size(m)
}
func (m *TestDataFilterValuesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_TestDataFilterValuesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_TestDataFilterValuesRequest proto.InternalMessageInfo

func (m *TestDataFilterValuesRequest) GetPluginId() string {
	if m != nil {
		return m.PluginId
	}
	return ""
}

func (m *TestDataFilterValuesRequest) GetPluginName() string {
	if m != nil {
		return m.PluginName
	}
	return ""
}

func (m *TestDataFilterValuesRequest) GetMessageId() string {
	if m != nil {
		return m.MessageId
	}
	return ""
}

func (m *TestDataFilterValuesRequest) GetTestDataDomainId() string {
	if m != nil {
		return m.TestDataDomainId
	}
	return ""
}

func (m *TestDataFilterValuesRequest) GetStartLineOfResultSet() int64 {
	if m != nil {
		return m.StartLineOfResultSet
	}
	return 0
}

func (m *TestDataFilterValuesRequest) GetMaxNumberOffLinesInResult() int64 {
	if m != nil {
		return m.MaxNumberOffLinesInResult
	}
	return 0
}

func (m *TestDataFilterValuesRequest) GetTestDataType() TestDataFormatTypeEnum {
	if m != nil {
		return m.TestDataType
	}
	return TestDataFormatTypeEnum_LIST
}

func (m *TestDataFilterValuesRequest) GetTestDataFIlterHeaders() []*TestDataFilterHeader {
	if m != nil {
		return m.TestDataFIlterHeaders
	}
	return nil
}

func (m *TestDataFilterValuesRequest) GetOrginalCreateDateTime() string {
	if m != nil {
		return m.OrginalCreateDateTime
	}
	return ""
}

// Message to hold a Testdata header with its chosen testdata values
type TestDataFilterHeader struct {
	TestDataFilterHeaderId     string                       `protobuf:"bytes,1,opt,name=TestDataFilterHeaderId,proto3" json:"TestDataFilterHeaderId,omitempty"`
	TestDataFilterHeaderValues []*TestDataFilterHeaderValue `protobuf:"bytes,2,rep,name=TestDataFilterHeaderValues,proto3" json:"TestDataFilterHeaderValues,omitempty"`
	XXX_NoUnkeyedLiteral       struct{}                     `json:"-"`
	XXX_unrecognized           []byte                       `json:"-"`
	XXX_sizecache              int32                        `json:"-"`
}

func (m *TestDataFilterHeader) Reset()         { *m = TestDataFilterHeader{} }
func (m *TestDataFilterHeader) String() string { return proto.CompactTextString(m) }
func (*TestDataFilterHeader) ProtoMessage()    {}
func (*TestDataFilterHeader) Descriptor() ([]byte, []int) {
	return fileDescriptor_9bd1c4b0181b0d9a, []int{5}
}

func (m *TestDataFilterHeader) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TestDataFilterHeader.Unmarshal(m, b)
}
func (m *TestDataFilterHeader) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TestDataFilterHeader.Marshal(b, m, deterministic)
}
func (m *TestDataFilterHeader) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TestDataFilterHeader.Merge(m, src)
}
func (m *TestDataFilterHeader) XXX_Size() int {
	return xxx_messageInfo_TestDataFilterHeader.Size(m)
}
func (m *TestDataFilterHeader) XXX_DiscardUnknown() {
	xxx_messageInfo_TestDataFilterHeader.DiscardUnknown(m)
}

var xxx_messageInfo_TestDataFilterHeader proto.InternalMessageInfo

func (m *TestDataFilterHeader) GetTestDataFilterHeaderId() string {
	if m != nil {
		return m.TestDataFilterHeaderId
	}
	return ""
}

func (m *TestDataFilterHeader) GetTestDataFilterHeaderValues() []*TestDataFilterHeaderValue {
	if m != nil {
		return m.TestDataFilterHeaderValues
	}
	return nil
}

// Message to hold a specific value (Id and Value)
type TestDataFilterHeaderValue struct {
	TestDataFilterHeaderValueId   string   `protobuf:"bytes,1,opt,name=TestDataFilterHeaderValueId,proto3" json:"TestDataFilterHeaderValueId,omitempty"`
	TestDataFilterHeaderValueName string   `protobuf:"bytes,2,opt,name=TestDataFilterHeaderValueName,proto3" json:"TestDataFilterHeaderValueName,omitempty"`
	XXX_NoUnkeyedLiteral          struct{} `json:"-"`
	XXX_unrecognized              []byte   `json:"-"`
	XXX_sizecache                 int32    `json:"-"`
}

func (m *TestDataFilterHeaderValue) Reset()         { *m = TestDataFilterHeaderValue{} }
func (m *TestDataFilterHeaderValue) String() string { return proto.CompactTextString(m) }
func (*TestDataFilterHeaderValue) ProtoMessage()    {}
func (*TestDataFilterHeaderValue) Descriptor() ([]byte, []int) {
	return fileDescriptor_9bd1c4b0181b0d9a, []int{6}
}

func (m *TestDataFilterHeaderValue) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TestDataFilterHeaderValue.Unmarshal(m, b)
}
func (m *TestDataFilterHeaderValue) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TestDataFilterHeaderValue.Marshal(b, m, deterministic)
}
func (m *TestDataFilterHeaderValue) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TestDataFilterHeaderValue.Merge(m, src)
}
func (m *TestDataFilterHeaderValue) XXX_Size() int {
	return xxx_messageInfo_TestDataFilterHeaderValue.Size(m)
}
func (m *TestDataFilterHeaderValue) XXX_DiscardUnknown() {
	xxx_messageInfo_TestDataFilterHeaderValue.DiscardUnknown(m)
}

var xxx_messageInfo_TestDataFilterHeaderValue proto.InternalMessageInfo

func (m *TestDataFilterHeaderValue) GetTestDataFilterHeaderValueId() string {
	if m != nil {
		return m.TestDataFilterHeaderValueId
	}
	return ""
}

func (m *TestDataFilterHeaderValue) GetTestDataFilterHeaderValueName() string {
	if m != nil {
		return m.TestDataFilterHeaderValueName
	}
	return ""
}

// *********************************************************
//  rpc PleaseReRegisterClientAddress(ReRegisterToGatewayMessage)returns(AckNackResponse)
// START
// **********
// Used when a Fenix or a Gateway comes online, message is sent to know clients
type ReRegisterToGatewayMessage struct {
	GatewayAddress       string   `protobuf:"bytes,1,opt,name=GatewayAddress,proto3" json:"GatewayAddress,omitempty"`
	GatewayPort          int32    `protobuf:"varint,2,opt,name=GatewayPort,proto3" json:"GatewayPort,omitempty"`
	GatewayId            string   `protobuf:"bytes,3,opt,name=GatewayId,proto3" json:"GatewayId,omitempty"`
	GatewayName          string   `protobuf:"bytes,4,opt,name=GatewayName,proto3" json:"GatewayName,omitempty"`
	CreatedDateTime      string   `protobuf:"bytes,5,opt,name=CreatedDateTime,proto3" json:"CreatedDateTime,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReRegisterToGatewayMessage) Reset()         { *m = ReRegisterToGatewayMessage{} }
func (m *ReRegisterToGatewayMessage) String() string { return proto.CompactTextString(m) }
func (*ReRegisterToGatewayMessage) ProtoMessage()    {}
func (*ReRegisterToGatewayMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_9bd1c4b0181b0d9a, []int{7}
}

func (m *ReRegisterToGatewayMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReRegisterToGatewayMessage.Unmarshal(m, b)
}
func (m *ReRegisterToGatewayMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReRegisterToGatewayMessage.Marshal(b, m, deterministic)
}
func (m *ReRegisterToGatewayMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReRegisterToGatewayMessage.Merge(m, src)
}
func (m *ReRegisterToGatewayMessage) XXX_Size() int {
	return xxx_messageInfo_ReRegisterToGatewayMessage.Size(m)
}
func (m *ReRegisterToGatewayMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_ReRegisterToGatewayMessage.DiscardUnknown(m)
}

var xxx_messageInfo_ReRegisterToGatewayMessage proto.InternalMessageInfo

func (m *ReRegisterToGatewayMessage) GetGatewayAddress() string {
	if m != nil {
		return m.GatewayAddress
	}
	return ""
}

func (m *ReRegisterToGatewayMessage) GetGatewayPort() int32 {
	if m != nil {
		return m.GatewayPort
	}
	return 0
}

func (m *ReRegisterToGatewayMessage) GetGatewayId() string {
	if m != nil {
		return m.GatewayId
	}
	return ""
}

func (m *ReRegisterToGatewayMessage) GetGatewayName() string {
	if m != nil {
		return m.GatewayName
	}
	return ""
}

func (m *ReRegisterToGatewayMessage) GetCreatedDateTime() string {
	if m != nil {
		return m.CreatedDateTime
	}
	return ""
}

func init() {
	proto.RegisterEnum("Gateway_gRPC_api.TestInstructionAttributeTypeEnum", TestInstructionAttributeTypeEnum_name, TestInstructionAttributeTypeEnum_value)
	proto.RegisterEnum("Gateway_gRPC_api.DbStatusEnum", DbStatusEnum_name, DbStatusEnum_value)
	proto.RegisterType((*TestInstruction_RT)(nil), "Gateway_gRPC_api.TestInstruction_RT")
	proto.RegisterType((*TestInstructionAttribute_RT)(nil), "Gateway_gRPC_api.TestInstructionAttribute_RT")
	proto.RegisterType((*TestInstructionRTMetadata)(nil), "Gateway_gRPC_api.TestInstructionRTMetadata")
	proto.RegisterType((*SupportedTestDataDomainsRequest)(nil), "Gateway_gRPC_api.SupportedTestDataDomainsRequest")
	proto.RegisterType((*TestDataFilterValuesRequest)(nil), "Gateway_gRPC_api.TestDataFilterValuesRequest")
	proto.RegisterType((*TestDataFilterHeader)(nil), "Gateway_gRPC_api.TestDataFilterHeader")
	proto.RegisterType((*TestDataFilterHeaderValue)(nil), "Gateway_gRPC_api.TestDataFilterHeaderValue")
	proto.RegisterType((*ReRegisterToGatewayMessage)(nil), "Gateway_gRPC_api.ReRegisterToGatewayMessage")
}

func init() { proto.RegisterFile("gateway_towards_plugin_grpc.proto", fileDescriptor_9bd1c4b0181b0d9a) }

var fileDescriptor_9bd1c4b0181b0d9a = []byte{
	// 1116 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xcc, 0x57, 0xcf, 0x6e, 0xdb, 0xc6,
	0x13, 0x8e, 0xa4, 0x9f, 0x63, 0x7b, 0xec, 0x9f, 0xa3, 0x6e, 0x93, 0x96, 0x56, 0x6c, 0x57, 0x16,
	0x82, 0x40, 0x70, 0x5a, 0xa3, 0x51, 0x8b, 0xa2, 0x87, 0x1e, 0x6a, 0x4b, 0xb2, 0x43, 0x40, 0x96,
	0x8c, 0x25, 0x9d, 0x43, 0x51, 0x80, 0x58, 0x8b, 0x63, 0x95, 0xb0, 0xc4, 0x55, 0x97, 0xcb, 0xc6,
	0x39, 0x17, 0x7d, 0x88, 0x9e, 0xfb, 0x18, 0x45, 0xdf, 0xa1, 0xef, 0xd0, 0x7b, 0xaf, 0xbd, 0x16,
	0x5c, 0xfe, 0x11, 0x45, 0x91, 0xb4, 0x8f, 0xbd, 0x89, 0xf3, 0x7d, 0x33, 0x3b, 0x33, 0x9c, 0xf9,
	0x56, 0x84, 0xc3, 0x09, 0x93, 0xf8, 0x8e, 0xbd, 0xb7, 0x24, 0x7f, 0xc7, 0x84, 0xed, 0x59, 0xf3,
	0xa9, 0x3f, 0x71, 0x5c, 0x6b, 0x22, 0xe6, 0xe3, 0xe3, 0xb9, 0xe0, 0x92, 0x93, 0xfa, 0x79, 0x44,
	0x99, 0xd0, 0xcb, 0xae, 0xc5, 0xe6, 0x4e, 0x63, 0x37, 0x76, 0x1a, 0xf3, 0xd9, 0x8c, 0xa7, 0xc9,
	0xad, 0x5f, 0xd6, 0x81, 0x98, 0xe8, 0x49, 0xdd, 0xf5, 0xa4, 0xf0, 0xc7, 0xd2, 0xe1, 0xae, 0x45,
	0x4d, 0x72, 0x04, 0xf5, 0x91, 0x70, 0x26, 0x8e, 0xcb, 0xa6, 0x06, 0xba, 0x36, 0x0a, 0xdd, 0xd6,
	0x2a, 0xcd, 0x4a, 0x7b, 0x93, 0xae, 0xd8, 0xc9, 0x31, 0x90, 0x65, 0xdb, 0x90, 0xcd, 0x50, 0xab,
	0x2a, 0x76, 0x0e, 0x42, 0x1a, 0xb0, 0x91, 0xc4, 0xac, 0x29, 0x56, 0xf2, 0x4c, 0x0e, 0x00, 0x52,
	0x31, 0xfe, 0xa7, 0xd0, 0x94, 0x85, 0x7c, 0x0d, 0x1f, 0x67, 0xb2, 0x35, 0xdf, 0xcf, 0xf1, 0xdc,
	0x77, 0x6c, 0x6d, 0x4d, 0x91, 0x8b, 0x60, 0xf2, 0x39, 0x7c, 0x98, 0x81, 0x94, 0xd7, 0x63, 0xe5,
	0x95, 0x07, 0x15, 0x9c, 0xa5, 0x12, 0x5b, 0x2f, 0x3c, 0x2b, 0xae, 0xf0, 0x52, 0xbd, 0x16, 0xdd,
	0xd6, 0x36, 0xc2, 0x0a, 0xe3, 0xe7, 0xa0, 0xc2, 0xf0, 0xb7, 0x0a, 0xb4, 0x19, 0x56, 0xb8, 0xb0,
	0x90, 0xd7, 0xf0, 0x34, 0x08, 0x7b, 0xc1, 0x1c, 0xf7, 0x5c, 0x70, 0x7f, 0x1e, 0xa4, 0x62, 0x51,
	0x53, 0x83, 0x45, 0xa2, 0x4b, 0x18, 0x35, 0xc9, 0x2d, 0xec, 0x66, 0x32, 0x39, 0x91, 0x52, 0x38,
	0xd7, 0xbe, 0x44, 0x4f, 0xdb, 0x6a, 0xd6, 0xda, 0x5b, 0x9d, 0xcf, 0x8e, 0xb3, 0x43, 0x71, 0x5c,
	0xe4, 0x62, 0x51, 0x93, 0x16, 0xc7, 0x23, 0x67, 0x70, 0x90, 0x01, 0xbb, 0x02, 0x99, 0x44, 0xbb,
	0xc7, 0x24, 0x9a, 0xce, 0x0c, 0xb5, 0x6d, 0x95, 0xe9, 0x3d, 0x2c, 0xf2, 0x2d, 0x3c, 0xcf, 0x30,
	0x0c, 0x74, 0x65, 0x12, 0xe4, 0xff, 0xcd, 0x5a, 0x7b, 0x93, 0x96, 0x51, 0x82, 0xb9, 0xeb, 0xfe,
	0xc0, 0xb9, 0x87, 0xee, 0x80, 0xb9, 0xb6, 0xe3, 0x4e, 0xbe, 0xe3, 0x2e, 0x6a, 0x3b, 0xe1, 0xdc,
	0xad, 0x22, 0xe4, 0x1c, 0x36, 0x2e, 0x50, 0x32, 0x9b, 0x49, 0xa6, 0x3d, 0x69, 0x56, 0xda, 0x5b,
	0x9d, 0x57, 0xf7, 0x76, 0x85, 0x9a, 0xb1, 0x0b, 0x4d, 0x9c, 0xc9, 0x97, 0xf0, 0x6c, 0x24, 0xd4,
	0x54, 0x87, 0x45, 0x25, 0x49, 0xd7, 0xd5, 0xd9, 0xf9, 0x20, 0xd9, 0x83, 0xcd, 0x0b, 0xf4, 0x3c,
	0x36, 0x41, 0xdd, 0xd6, 0x3e, 0x50, 0xcc, 0x85, 0xa1, 0xf5, 0x57, 0x75, 0xa5, 0x1f, 0xe9, 0x37,
	0x42, 0x4e, 0x61, 0xaf, 0x08, 0x56, 0x73, 0x1c, 0x2e, 0x67, 0x29, 0xa7, 0x2c, 0x46, 0x6a, 0x65,
	0x4b, 0x39, 0xe4, 0xa7, 0xe2, 0x18, 0xc1, 0xf8, 0xab, 0x85, 0xde, 0xe9, 0x74, 0x1e, 0x3e, 0x6e,
	0x81, 0x57, 0xdf, 0xf5, 0x67, 0xb4, 0x34, 0x2e, 0xe9, 0xc1, 0x7e, 0x11, 0xfe, 0x96, 0x4d, 0xfd,
	0x58, 0x2b, 0xca, 0x49, 0xad, 0x9f, 0xab, 0x2b, 0xab, 0xb2, 0x78, 0xc3, 0xa4, 0x03, 0x4f, 0x33,
	0x53, 0x7a, 0x86, 0xae, 0x73, 0x17, 0xf5, 0x36, 0x17, 0x0b, 0x66, 0x21, 0x63, 0x0f, 0x77, 0x39,
	0x6a, 0x66, 0x3e, 0x18, 0x48, 0xcb, 0x80, 0x79, 0xf2, 0x6a, 0x6e, 0xa7, 0x41, 0xdd, 0xed, 0x9d,
	0x46, 0x8a, 0x58, 0x04, 0x93, 0x53, 0xd8, 0xee, 0x5d, 0x1b, 0x92, 0x49, 0xdf, 0x0b, 0xba, 0xa6,
	0xca, 0xde, 0xe9, 0x1c, 0xac, 0xf6, 0x3b, 0xcd, 0xa2, 0x4b, 0x3e, 0xad, 0x3f, 0xaa, 0xf0, 0x89,
	0xe1, 0xcf, 0xe7, 0x5c, 0x48, 0xb4, 0x83, 0x76, 0xf4, 0x98, 0x64, 0x3d, 0x3e, 0x63, 0x8e, 0xeb,
	0x51, 0xfc, 0xd1, 0x47, 0x4f, 0xfe, 0x67, 0x2f, 0x80, 0xb4, 0xb4, 0xae, 0x95, 0x4a, 0xeb, 0xe3,
	0x15, 0x69, 0x5d, 0xda, 0xc0, 0xf5, 0xcc, 0x06, 0x92, 0x36, 0x3c, 0xc9, 0x2a, 0x59, 0xa8, 0xdd,
	0x59, 0x73, 0xeb, 0x9f, 0x5a, 0xb8, 0xab, 0x41, 0xdb, 0xce, 0x9c, 0xa9, 0x44, 0xa1, 0xa6, 0x2b,
	0xe9, 0x5d, 0x3a, 0xc7, 0x4a, 0x69, 0x8e, 0xd5, 0xf2, 0x1c, 0x6b, 0xd9, 0x1c, 0x8f, 0xa0, 0xbe,
	0xfc, 0xbe, 0x74, 0x3b, 0xea, 0xd1, 0x8a, 0x3d, 0x98, 0x66, 0x43, 0x32, 0x21, 0x07, 0x8e, 0x8b,
	0xa3, 0x1b, 0x8a, 0x9e, 0x3f, 0x95, 0x06, 0x4a, 0xd5, 0x97, 0x1a, 0xcd, 0xc5, 0xc8, 0x37, 0xb0,
	0x7b, 0xc1, 0xee, 0x86, 0xfe, 0xec, 0x1a, 0xc5, 0xe8, 0xe6, 0x26, 0x80, 0x3d, 0xdd, 0x0d, 0x71,
	0xd5, 0xb1, 0x1a, 0x2d, 0x26, 0x90, 0x01, 0x6c, 0xc7, 0x59, 0x28, 0x2d, 0xd8, 0x50, 0xb3, 0xd9,
	0xce, 0xd7, 0x02, 0xd5, 0x3c, 0x2e, 0x66, 0x4c, 0x26, 0x0a, 0xb0, 0xe4, 0x4d, 0xbe, 0x87, 0x67,
	0x09, 0x4f, 0x0f, 0x9a, 0xfc, 0x06, 0x99, 0x8d, 0xc2, 0xd3, 0x36, 0xd5, 0x8d, 0xf6, 0xb2, 0x24,
	0xac, 0xb3, 0xa0, 0xd3, 0xfc, 0x20, 0xc5, 0x1a, 0x0e, 0x25, 0x1a, 0xde, 0xfa, 0xbd, 0x12, 0xde,
	0xce, 0xd9, 0x53, 0xc8, 0x57, 0xf0, 0x51, 0x9e, 0x3d, 0x19, 0x80, 0x02, 0x94, 0xdc, 0x42, 0x23,
	0x0f, 0x09, 0xe7, 0x49, 0xab, 0xaa, 0x4a, 0x5f, 0x3d, 0xac, 0x52, 0xe5, 0x43, 0x4b, 0xc2, 0xb5,
	0x7e, 0xab, 0x84, 0xea, 0x97, 0x0b, 0xc7, 0x17, 0x72, 0x2e, 0x98, 0xd4, 0x51, 0x46, 0x89, 0x35,
	0x3a, 0x17, 0x4e, 0x8d, 0x7b, 0x39, 0xa9, 0xf5, 0x67, 0x05, 0x1a, 0x14, 0x29, 0x4e, 0x1c, 0x4f,
	0xa2, 0x30, 0x79, 0x54, 0x7c, 0xb4, 0x04, 0xe4, 0x25, 0xec, 0x44, 0x96, 0x13, 0xdb, 0x16, 0xe8,
	0x79, 0x51, 0x66, 0x19, 0x2b, 0x69, 0xc2, 0x56, 0x64, 0xb9, 0xe4, 0x42, 0xaa, 0xa3, 0xd7, 0x68,
	0xda, 0x14, 0xac, 0x5a, 0xf4, 0xb8, 0x58, 0xb5, 0xc4, 0x90, 0xf2, 0x4f, 0x29, 0x51, 0xda, 0x94,
	0x27, 0x18, 0x6b, 0xb9, 0x82, 0x71, 0x34, 0x82, 0xe6, 0x7d, 0xd7, 0x1f, 0xd9, 0x82, 0x75, 0x13,
	0xef, 0xe4, 0x29, 0xbf, 0xab, 0x3f, 0x22, 0xdb, 0xb0, 0xd1, 0xe5, 0xb3, 0x6b, 0x1e, 0x3c, 0x55,
	0x48, 0x1d, 0xb6, 0xcf, 0x9c, 0x29, 0x1a, 0x38, 0xc5, 0xb1, 0xe4, 0xa2, 0x5e, 0x3d, 0xfa, 0xb5,
	0xb2, 0x7c, 0x0d, 0x90, 0x36, 0xbc, 0x30, 0xfb, 0x86, 0xa9, 0x0f, 0x0d, 0x93, 0x5e, 0x75, 0x4d,
	0x7d, 0x34, 0xb4, 0x68, 0xbf, 0xdb, 0xd7, 0xdf, 0xf6, 0x7b, 0xd6, 0x19, 0x1d, 0x5d, 0x58, 0x97,
	0x27, 0xb4, 0x3f, 0x34, 0xeb, 0x8f, 0xc8, 0x21, 0xec, 0x67, 0x99, 0x46, 0x7f, 0x68, 0x5a, 0xe6,
	0xc8, 0xea, 0xbe, 0xd1, 0x07, 0xbd, 0x7a, 0x85, 0x1c, 0x40, 0x83, 0xf6, 0x8d, 0xab, 0x81, 0x99,
	0x89, 0x11, 0xe2, 0x55, 0xb2, 0x07, 0x5a, 0x84, 0xc7, 0x9e, 0xe6, 0x28, 0x3e, 0xa0, 0xd6, 0xf9,
	0xbb, 0x0a, 0x24, 0x6a, 0x93, 0xc9, 0x83, 0x5e, 0x87, 0x57, 0xde, 0x0c, 0x9a, 0x81, 0x8c, 0x67,
	0xff, 0x32, 0x87, 0x5f, 0x31, 0x11, 0xe7, 0xc5, 0xbd, 0x7f, 0x1b, 0x2c, 0x6a, 0x36, 0x0e, 0x57,
	0x59, 0x27, 0xe3, 0xdb, 0x21, 0x1b, 0xdf, 0x52, 0xf4, 0xe6, 0xdc, 0xf5, 0xb0, 0xf5, 0x88, 0xf8,
	0xf0, 0xfc, 0x1c, 0x65, 0xd1, 0x2d, 0x47, 0x5e, 0xaf, 0xc6, 0xb8, 0xe7, 0x46, 0x7c, 0xd8, 0xb1,
	0x02, 0xf6, 0x2f, 0xa7, 0xc8, 0x3c, 0x5c, 0x4c, 0x70, 0x77, 0xea, 0xa0, 0x2b, 0xe3, 0xb1, 0xfc,
	0x74, 0x35, 0x4a, 0xf1, 0xb0, 0x3f, 0xe8, 0xcc, 0xeb, 0xc7, 0xea, 0x4b, 0xee, 0x8b, 0x7f, 0x03,
	0x00, 0x00, 0xff, 0xff, 0x43, 0x57, 0x12, 0x18, 0x1b, 0x0e, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// GatewayTowayPluginClient is the client API for GatewayTowayPlugin service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type GatewayTowayPluginClient interface {
	// TestInstructions flows from Fenix Inception towards Plugins
	SendTestInstructionTowardsPlugin(ctx context.Context, in *TestInstruction_RT, opts ...grpc.CallOption) (*AckNackResponse, error)
	GetSupportedTestDataDomains(ctx context.Context, in *SupportedTestDataDomainsRequest, opts ...grpc.CallOption) (*AckNackResponse, error)
	// At startup the gateway asks clients, Plugin or Sub-Gateway, to reregister to be able to check which of them that are online
	PleaseReRegisterClientAddress(ctx context.Context, in *ReRegisterToGatewayMessage, opts ...grpc.CallOption) (*AckNackResponse, error)
}

type gatewayTowayPluginClient struct {
	cc *grpc.ClientConn
}

func NewGatewayTowayPluginClient(cc *grpc.ClientConn) GatewayTowayPluginClient {
	return &gatewayTowayPluginClient{cc}
}

func (c *gatewayTowayPluginClient) SendTestInstructionTowardsPlugin(ctx context.Context, in *TestInstruction_RT, opts ...grpc.CallOption) (*AckNackResponse, error) {
	out := new(AckNackResponse)
	err := c.cc.Invoke(ctx, "/Gateway_gRPC_api.GatewayTowayPlugin/SendTestInstructionTowardsPlugin", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gatewayTowayPluginClient) GetSupportedTestDataDomains(ctx context.Context, in *SupportedTestDataDomainsRequest, opts ...grpc.CallOption) (*AckNackResponse, error) {
	out := new(AckNackResponse)
	err := c.cc.Invoke(ctx, "/Gateway_gRPC_api.GatewayTowayPlugin/GetSupportedTestDataDomains", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gatewayTowayPluginClient) PleaseReRegisterClientAddress(ctx context.Context, in *ReRegisterToGatewayMessage, opts ...grpc.CallOption) (*AckNackResponse, error) {
	out := new(AckNackResponse)
	err := c.cc.Invoke(ctx, "/Gateway_gRPC_api.GatewayTowayPlugin/PleaseReRegisterClientAddress", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GatewayTowayPluginServer is the server API for GatewayTowayPlugin service.
type GatewayTowayPluginServer interface {
	// TestInstructions flows from Fenix Inception towards Plugins
	SendTestInstructionTowardsPlugin(context.Context, *TestInstruction_RT) (*AckNackResponse, error)
	GetSupportedTestDataDomains(context.Context, *SupportedTestDataDomainsRequest) (*AckNackResponse, error)
	// At startup the gateway asks clients, Plugin or Sub-Gateway, to reregister to be able to check which of them that are online
	PleaseReRegisterClientAddress(context.Context, *ReRegisterToGatewayMessage) (*AckNackResponse, error)
}

func RegisterGatewayTowayPluginServer(s *grpc.Server, srv GatewayTowayPluginServer) {
	s.RegisterService(&_GatewayTowayPlugin_serviceDesc, srv)
}

func _GatewayTowayPlugin_SendTestInstructionTowardsPlugin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TestInstruction_RT)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GatewayTowayPluginServer).SendTestInstructionTowardsPlugin(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Gateway_gRPC_api.GatewayTowayPlugin/SendTestInstructionTowardsPlugin",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GatewayTowayPluginServer).SendTestInstructionTowardsPlugin(ctx, req.(*TestInstruction_RT))
	}
	return interceptor(ctx, in, info, handler)
}

func _GatewayTowayPlugin_GetSupportedTestDataDomains_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SupportedTestDataDomainsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GatewayTowayPluginServer).GetSupportedTestDataDomains(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Gateway_gRPC_api.GatewayTowayPlugin/GetSupportedTestDataDomains",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GatewayTowayPluginServer).GetSupportedTestDataDomains(ctx, req.(*SupportedTestDataDomainsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GatewayTowayPlugin_PleaseReRegisterClientAddress_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReRegisterToGatewayMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GatewayTowayPluginServer).PleaseReRegisterClientAddress(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Gateway_gRPC_api.GatewayTowayPlugin/PleaseReRegisterClientAddress",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GatewayTowayPluginServer).PleaseReRegisterClientAddress(ctx, req.(*ReRegisterToGatewayMessage))
	}
	return interceptor(ctx, in, info, handler)
}

var _GatewayTowayPlugin_serviceDesc = grpc.ServiceDesc{
	ServiceName: "Gateway_gRPC_api.GatewayTowayPlugin",
	HandlerType: (*GatewayTowayPluginServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SendTestInstructionTowardsPlugin",
			Handler:    _GatewayTowayPlugin_SendTestInstructionTowardsPlugin_Handler,
		},
		{
			MethodName: "GetSupportedTestDataDomains",
			Handler:    _GatewayTowayPlugin_GetSupportedTestDataDomains_Handler,
		},
		{
			MethodName: "PleaseReRegisterClientAddress",
			Handler:    _GatewayTowayPlugin_PleaseReRegisterClientAddress_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "gateway_towards_plugin_grpc.proto",
}
