// Code generated by protoc-gen-go. DO NOT EDIT.
// source: gateway_common_grpc.proto

package Gateway_gRPC_api

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "github.com/golang/protobuf/ptypes/timestamp"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Used for defining the current version of the proto-file
type CurrentVersionEnum int32

const (
	CurrentVersionEnum_VERSION_0_1_0 CurrentVersionEnum = 0
)

var CurrentVersionEnum_name = map[int32]string{
	0: "VERSION_0_1_0",
}

var CurrentVersionEnum_value = map[string]int32{
	"VERSION_0_1_0": 0,
}

func (x CurrentVersionEnum) String() string {
	return proto.EnumName(CurrentVersionEnum_name, int32(x))
}

func (CurrentVersionEnum) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_3284122e3ea2603f, []int{0}
}

// Defines the different ways testdata should be formated back to Fenix
type TestDataFormatTypeEnum int32

const (
	TestDataFormatTypeEnum_LIST TestDataFormatTypeEnum = 0
)

var TestDataFormatTypeEnum_name = map[int32]string{
	0: "LIST",
}

var TestDataFormatTypeEnum_value = map[string]int32{
	"LIST": 0,
}

func (x TestDataFormatTypeEnum) String() string {
	return proto.EnumName(TestDataFormatTypeEnum_name, int32(x))
}

func (TestDataFormatTypeEnum) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_3284122e3ea2603f, []int{1}
}

// Parameter used for Empty inputs
type EmptyParameter struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EmptyParameter) Reset()         { *m = EmptyParameter{} }
func (m *EmptyParameter) String() string { return proto.CompactTextString(m) }
func (*EmptyParameter) ProtoMessage()    {}
func (*EmptyParameter) Descriptor() ([]byte, []int) {
	return fileDescriptor_3284122e3ea2603f, []int{0}
}

func (m *EmptyParameter) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EmptyParameter.Unmarshal(m, b)
}
func (m *EmptyParameter) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EmptyParameter.Marshal(b, m, deterministic)
}
func (m *EmptyParameter) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EmptyParameter.Merge(m, src)
}
func (m *EmptyParameter) XXX_Size() int {
	return xxx_messageInfo_EmptyParameter.Size(m)
}
func (m *EmptyParameter) XXX_DiscardUnknown() {
	xxx_messageInfo_EmptyParameter.DiscardUnknown(m)
}

var xxx_messageInfo_EmptyParameter proto.InternalMessageInfo

// Ack/Nack- Response message with comment
type AckNackResponse struct {
	Acknack              bool     `protobuf:"varint,1,opt,name=acknack,proto3" json:"acknack,omitempty"`
	Comments             string   `protobuf:"bytes,2,opt,name=comments,proto3" json:"comments,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AckNackResponse) Reset()         { *m = AckNackResponse{} }
func (m *AckNackResponse) String() string { return proto.CompactTextString(m) }
func (*AckNackResponse) ProtoMessage()    {}
func (*AckNackResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_3284122e3ea2603f, []int{1}
}

func (m *AckNackResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AckNackResponse.Unmarshal(m, b)
}
func (m *AckNackResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AckNackResponse.Marshal(b, m, deterministic)
}
func (m *AckNackResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AckNackResponse.Merge(m, src)
}
func (m *AckNackResponse) XXX_Size() int {
	return xxx_messageInfo_AckNackResponse.Size(m)
}
func (m *AckNackResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AckNackResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AckNackResponse proto.InternalMessageInfo

func (m *AckNackResponse) GetAcknack() bool {
	if m != nil {
		return m.Acknack
	}
	return false
}

func (m *AckNackResponse) GetComments() string {
	if m != nil {
		return m.Comments
	}
	return ""
}

func init() {
	proto.RegisterEnum("Gateway_gRPC_api.CurrentVersionEnum", CurrentVersionEnum_name, CurrentVersionEnum_value)
	proto.RegisterEnum("Gateway_gRPC_api.TestDataFormatTypeEnum", TestDataFormatTypeEnum_name, TestDataFormatTypeEnum_value)
	proto.RegisterType((*EmptyParameter)(nil), "Gateway_gRPC_api.EmptyParameter")
	proto.RegisterType((*AckNackResponse)(nil), "Gateway_gRPC_api.AckNackResponse")
}

func init() { proto.RegisterFile("gateway_common_grpc.proto", fileDescriptor_3284122e3ea2603f) }

var fileDescriptor_3284122e3ea2603f = []byte{
	// 221 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x3c, 0x8e, 0x4f, 0x4b, 0xc3, 0x40,
	0x10, 0x47, 0x1b, 0x11, 0x8d, 0x03, 0xda, 0xb8, 0x07, 0x89, 0x3d, 0x95, 0x5c, 0x2c, 0x3d, 0x48,
	0xc5, 0x4f, 0x20, 0x35, 0x96, 0x82, 0xd4, 0xb2, 0x0d, 0xbd, 0x2e, 0xe3, 0x32, 0x84, 0x10, 0xf6,
	0x0f, 0xb3, 0x53, 0x24, 0xdf, 0x5e, 0xac, 0xda, 0xe3, 0xe3, 0xf7, 0xe0, 0xf7, 0xe0, 0xbe, 0x45,
	0xa1, 0x2f, 0x1c, 0x8c, 0x0d, 0xce, 0x05, 0x6f, 0x5a, 0x8e, 0xf6, 0x31, 0x72, 0x90, 0xa0, 0x8a,
	0xd5, 0xdf, 0xd4, 0xea, 0xed, 0xd2, 0x60, 0xec, 0x26, 0x63, 0xe9, 0x1c, 0x25, 0x41, 0x17, 0x7f,
	0x95, 0xaa, 0x80, 0x9b, 0xda, 0x45, 0x19, 0xb6, 0xc8, 0xe8, 0x48, 0x88, 0xab, 0x15, 0x8c, 0x5f,
	0x6c, 0xbf, 0x41, 0xdb, 0x6b, 0x4a, 0x31, 0xf8, 0x44, 0xaa, 0x84, 0x4b, 0xb4, 0xbd, 0x47, 0xdb,
	0x97, 0xd9, 0x34, 0x9b, 0xe5, 0xfa, 0x1f, 0xd5, 0x04, 0xf2, 0x9f, 0x5b, 0xf2, 0x92, 0xca, 0xb3,
	0x69, 0x36, 0xbb, 0xd2, 0x27, 0x9e, 0x3f, 0x80, 0x5a, 0x1e, 0x98, 0xc9, 0xcb, 0x9e, 0x38, 0x75,
	0xc1, 0xd7, 0xfe, 0xe0, 0xd4, 0x2d, 0x5c, 0xef, 0x6b, 0xbd, 0x5b, 0x7f, 0x6c, 0xcc, 0xc2, 0x3c,
	0x99, 0x45, 0x31, 0x9a, 0x57, 0x70, 0xd7, 0x50, 0x92, 0x57, 0x14, 0x7c, 0x0b, 0xec, 0x50, 0x9a,
	0x21, 0xd2, 0x51, 0xce, 0xe1, 0xfc, 0x7d, 0xbd, 0x6b, 0x8a, 0xd1, 0xe7, 0xc5, 0x31, 0xf7, 0xf9,
	0x3b, 0x00, 0x00, 0xff, 0xff, 0x56, 0x7b, 0x45, 0x04, 0xee, 0x00, 0x00, 0x00,
}
